set(SOURCES
	include/LoadEditorIDs.h
	include/PapyrusManager.h
	include/RNJesus.h
	include/SCOURGE.h
	include/SimpleIni.h
	include/YamlParser.h
	src/PCH.h
	src/main.cpp
	src/PapyrusManager.cpp
)
